# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(812, 501)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMinimumSize(QtCore.QSize(812, 501))
        main.setMaximumSize(QtCore.QSize(812, 501))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setStatusTip(_fromUtf8(""))
        main.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtGui.QWidget(main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.videoTreeW = QtGui.QTreeWidget(self.centralwidget)
        self.videoTreeW.setEnabled(True)
        self.videoTreeW.setGeometry(QtCore.QRect(10, 40, 791, 391))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoTreeW.sizePolicy().hasHeightForWidth())
        self.videoTreeW.setSizePolicy(sizePolicy)
        self.videoTreeW.setMinimumSize(QtCore.QSize(601, 121))
        self.videoTreeW.setMaximumSize(QtCore.QSize(900, 700))
        self.videoTreeW.setTabKeyNavigation(True)
        self.videoTreeW.setAlternatingRowColors(True)
        self.videoTreeW.setAnimated(True)
        self.videoTreeW.setObjectName(_fromUtf8("videoTreeW"))
        self.videoTreeW.header().setDefaultSectionSize(200)
        self.searchLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.searchLineEdit.setGeometry(QtCore.QRect(10, 10, 301, 20))
        self.searchLineEdit.setText(_fromUtf8(""))
        self.searchLineEdit.setObjectName(_fromUtf8("searchLineEdit"))
        main.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 812, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        main.setMenuBar(self.menuBar)
        self.ToolBar = QtGui.QToolBar(main)
        self.ToolBar.setEnabled(True)
        self.ToolBar.setMovable(False)
        self.ToolBar.setFloatable(False)
        self.ToolBar.setObjectName(_fromUtf8("ToolBar"))
        main.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        self.statusBar = QtGui.QStatusBar(main)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        main.setStatusBar(self.statusBar)
        self.addURL = QtGui.QAction(main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addURL.setIcon(icon1)
        self.addURL.setObjectName(_fromUtf8("addURL"))
        self.actionManage_servstat = QtGui.QAction(main)
        self.actionManage_servstat.setEnabled(False)
        self.actionManage_servstat.setObjectName(_fromUtf8("actionManage_servstat"))
        self.actionManage_user = QtGui.QAction(main)
        self.actionManage_user.setEnabled(False)
        self.actionManage_user.setObjectName(_fromUtf8("actionManage_user"))
        self.actionManage_messages = QtGui.QAction(main)
        self.actionManage_messages.setEnabled(False)
        self.actionManage_messages.setObjectName(_fromUtf8("actionManage_messages"))
        self.actionShow_left_pane = QtGui.QAction(main)
        self.actionShow_left_pane.setCheckable(True)
        self.actionShow_left_pane.setChecked(True)
        self.actionShow_left_pane.setObjectName(_fromUtf8("actionShow_left_pane"))
        self.actionCreate_Service_Station = QtGui.QAction(main)
        self.actionCreate_Service_Station.setEnabled(False)
        self.actionCreate_Service_Station.setObjectName(_fromUtf8("actionCreate_Service_Station"))
        self.actionEdit_service_station = QtGui.QAction(main)
        self.actionEdit_service_station.setEnabled(False)
        self.actionEdit_service_station.setObjectName(_fromUtf8("actionEdit_service_station"))
        self.actionDelete_service_station = QtGui.QAction(main)
        self.actionDelete_service_station.setEnabled(False)
        self.actionDelete_service_station.setObjectName(_fromUtf8("actionDelete_service_station"))
        self.actionHide_toolbar = QtGui.QAction(main)
        self.actionHide_toolbar.setCheckable(True)
        self.actionHide_toolbar.setChecked(True)
        self.actionHide_toolbar.setObjectName(_fromUtf8("actionHide_toolbar"))
        self.actionManage_Logs = QtGui.QAction(main)
        self.actionManage_Logs.setEnabled(False)
        self.actionManage_Logs.setObjectName(_fromUtf8("actionManage_Logs"))
        self.actionBackup_Data = QtGui.QAction(main)
        self.actionBackup_Data.setEnabled(False)
        self.actionBackup_Data.setObjectName(_fromUtf8("actionBackup_Data"))
        self.actionManage_services = QtGui.QAction(main)
        self.actionManage_services.setEnabled(False)
        self.actionManage_services.setObjectName(_fromUtf8("actionManage_services"))
        self.actionContact_us = QtGui.QAction(main)
        self.actionContact_us.setEnabled(False)
        self.actionContact_us.setObjectName(_fromUtf8("actionContact_us"))
        self.actionJob_application = QtGui.QAction(main)
        self.actionJob_application.setEnabled(False)
        self.actionJob_application.setObjectName(_fromUtf8("actionJob_application"))
        self.actionTraffic = QtGui.QAction(main)
        self.actionTraffic.setObjectName(_fromUtf8("actionTraffic"))
        self.actionBlocked_IPs = QtGui.QAction(main)
        self.actionBlocked_IPs.setObjectName(_fromUtf8("actionBlocked_IPs"))
        self.actionReportProblem = QtGui.QAction(main)
        self.actionReportProblem.setEnabled(True)
        self.actionReportProblem.setObjectName(_fromUtf8("actionReportProblem"))
        self.actionPreferences = QtGui.QAction(main)
        self.actionPreferences.setEnabled(True)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionChange_Password = QtGui.QAction(main)
        self.actionChange_Password.setEnabled(False)
        self.actionChange_Password.setObjectName(_fromUtf8("actionChange_Password"))
        self.actionService_Station = QtGui.QAction(main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/resources/servicestation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionService_Station.setIcon(icon2)
        self.actionService_Station.setVisible(False)
        self.actionService_Station.setObjectName(_fromUtf8("actionService_Station"))
        self.menuHelp.addAction(self.actionReportProblem)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.ToolBar.addAction(self.addURL)
        self.ToolBar.addSeparator()

        self.retranslateUi(main)
        QtCore.QObject.connect(self.actionHide_toolbar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolBar.setVisible)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        main.setWindowTitle(_translate("main", "Youtube Downloader", None))
        self.videoTreeW.setSortingEnabled(True)
        self.videoTreeW.headerItem().setText(0, _translate("main", "Video Name", None))
        self.videoTreeW.headerItem().setText(1, _translate("main", "Size", None))
        self.videoTreeW.headerItem().setText(2, _translate("main", "Status", None))
        self.videoTreeW.headerItem().setText(3, _translate("main", "Date Added", None))
        self.videoTreeW.headerItem().setText(4, _translate("main", "video_id", None))
        self.videoTreeW.headerItem().setText(5, _translate("main", "id", None))
        self.videoTreeW.headerItem().setText(6, _translate("main", "path", None))
        self.searchLineEdit.setPlaceholderText(_translate("main", "Search Video", None))
        self.menuHelp.setTitle(_translate("main", "Help", None))
        self.menuSettings.setTitle(_translate("main", "Settings", None))
        self.ToolBar.setWindowTitle(_translate("main", "Tool Bar", None))
        self.addURL.setText(_translate("main", "Add  URL", None))
        self.addURL.setToolTip(_translate("main", "Add Youtube URL to queue", None))
        self.actionManage_servstat.setText(_translate("main", "Manage service station", None))
        self.actionManage_servstat.setToolTip(_translate("main", "Manage location", None))
        self.actionManage_user.setText(_translate("main", "Manage users", None))
        self.actionManage_user.setToolTip(_translate("main", "Manage user", None))
        self.actionManage_messages.setText(_translate("main", "Manage tickets", None))
        self.actionManage_messages.setToolTip(_translate("main", "Manage messages", None))
        self.actionShow_left_pane.setText(_translate("main", "Toggle left pane", None))
        self.actionCreate_Service_Station.setText(_translate("main", "Create service station", None))
        self.actionEdit_service_station.setText(_translate("main", "Edit service station", None))
        self.actionDelete_service_station.setText(_translate("main", "Delete service station", None))
        self.actionHide_toolbar.setText(_translate("main", "Toggle Toolbar", None))
        self.actionManage_Logs.setText(_translate("main", "Manage Logs", None))
        self.actionBackup_Data.setText(_translate("main", "Backup Database", None))
        self.actionManage_services.setText(_translate("main", "Manage services", None))
        self.actionContact_us.setText(_translate("main", "Messages", None))
        self.actionJob_application.setText(_translate("main", "Job application", None))
        self.actionTraffic.setText(_translate("main", "Traffic", None))
        self.actionBlocked_IPs.setText(_translate("main", "Blocked IPs", None))
        self.actionReportProblem.setText(_translate("main", "Report a problem", None))
        self.actionPreferences.setText(_translate("main", "Preferences", None))
        self.actionChange_Password.setText(_translate("main", "Change Password", None))
        self.actionService_Station.setText(_translate("main", "Service Station", None))
        self.actionService_Station.setToolTip(_translate("main", "View history of service stations in your care", None))

import resources_rc
